// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"os/exec"
	"sync"

	"github.com/pivotal-cf/service-backup/process"
)

type FakeProcessManager struct {
	StartStub        func(*exec.Cmd) ([]byte, error)
	startMutex       sync.RWMutex
	startArgsForCall []struct {
		arg1 *exec.Cmd
	}
	startReturns struct {
		result1 []byte
		result2 error
	}
	startReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProcessManager) Start(arg1 *exec.Cmd) ([]byte, error) {
	fake.startMutex.Lock()
	ret, specificReturn := fake.startReturnsOnCall[len(fake.startArgsForCall)]
	fake.startArgsForCall = append(fake.startArgsForCall, struct {
		arg1 *exec.Cmd
	}{arg1})
	fake.recordInvocation("Start", []interface{}{arg1})
	fake.startMutex.Unlock()
	if fake.StartStub != nil {
		return fake.StartStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.startReturns.result1, fake.startReturns.result2
}

func (fake *FakeProcessManager) StartCallCount() int {
	fake.startMutex.RLock()
	defer fake.startMutex.RUnlock()
	return len(fake.startArgsForCall)
}

func (fake *FakeProcessManager) StartArgsForCall(i int) *exec.Cmd {
	fake.startMutex.RLock()
	defer fake.startMutex.RUnlock()
	return fake.startArgsForCall[i].arg1
}

func (fake *FakeProcessManager) StartReturns(result1 []byte, result2 error) {
	fake.StartStub = nil
	fake.startReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeProcessManager) StartReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.StartStub = nil
	if fake.startReturnsOnCall == nil {
		fake.startReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.startReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeProcessManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.startMutex.RLock()
	defer fake.startMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProcessManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ process.ProcessManager = new(FakeProcessManager)
