// This file was generated by counterfeiter
package backupfakes

import (
	"github.com/pivotal-cf-experimental/service-backup/backup"
	"sync"
)

type FakeHelper struct {
	DirSizeStub        func(localPath string) (int64, error)
	dirSizeMutex       sync.RWMutex
	dirSizeArgsForCall []struct {
		localPath string
	}
	dirSizeReturns struct {
		result1 int64
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHelper) DirSize(localPath string) (int64, error) {
	fake.dirSizeMutex.Lock()
	fake.dirSizeArgsForCall = append(fake.dirSizeArgsForCall, struct {
		localPath string
	}{localPath})
	fake.recordInvocation("DirSize", []interface{}{localPath})
	fake.dirSizeMutex.Unlock()
	if fake.DirSizeStub != nil {
		return fake.DirSizeStub(localPath)
	} else {
		return fake.dirSizeReturns.result1, fake.dirSizeReturns.result2
	}
}

func (fake *FakeHelper) DirSizeCallCount() int {
	fake.dirSizeMutex.RLock()
	defer fake.dirSizeMutex.RUnlock()
	return len(fake.dirSizeArgsForCall)
}

func (fake *FakeHelper) DirSizeArgsForCall(i int) string {
	fake.dirSizeMutex.RLock()
	defer fake.dirSizeMutex.RUnlock()
	return fake.dirSizeArgsForCall[i].localPath
}

func (fake *FakeHelper) DirSizeReturns(result1 int64, result2 error) {
	fake.DirSizeStub = nil
	fake.dirSizeReturns = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *FakeHelper) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.dirSizeMutex.RLock()
	defer fake.dirSizeMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeHelper) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ backup.Helper = new(FakeHelper)
