// This file was generated by counterfeiter
package backupfakes

import (
	"sync"

	"github.com/pivotal-cf-experimental/service-backup/backup"
)

type FakeBackuper struct {
	UploadStub        func(localPath string) error
	uploadMutex       sync.RWMutex
	uploadArgsForCall []struct {
		localPath string
	}
	uploadReturns struct {
		result1 error
	}
	SetLogSessionStub        func(sessionName, sessionIdentifier string)
	setLogSessionMutex       sync.RWMutex
	setLogSessionArgsForCall []struct {
		sessionName       string
		sessionIdentifier string
	}
	CloseLogSessionStub        func()
	closeLogSessionMutex       sync.RWMutex
	closeLogSessionArgsForCall []struct{}
	invocations                map[string][][]interface{}
	invocationsMutex           sync.RWMutex
}

func (fake *FakeBackuper) Upload(localPath string) error {
	fake.uploadMutex.Lock()
	fake.uploadArgsForCall = append(fake.uploadArgsForCall, struct {
		localPath string
	}{localPath})
	fake.recordInvocation("Upload", []interface{}{localPath})
	fake.uploadMutex.Unlock()
	if fake.UploadStub != nil {
		return fake.UploadStub(localPath)
	} else {
		return fake.uploadReturns.result1
	}
}

func (fake *FakeBackuper) UploadCallCount() int {
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	return len(fake.uploadArgsForCall)
}

func (fake *FakeBackuper) UploadArgsForCall(i int) string {
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	return fake.uploadArgsForCall[i].localPath
}

func (fake *FakeBackuper) UploadReturns(result1 error) {
	fake.UploadStub = nil
	fake.uploadReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBackuper) SetLogSession(sessionName string, sessionIdentifier string) {
	fake.setLogSessionMutex.Lock()
	fake.setLogSessionArgsForCall = append(fake.setLogSessionArgsForCall, struct {
		sessionName       string
		sessionIdentifier string
	}{sessionName, sessionIdentifier})
	fake.recordInvocation("SetLogSession", []interface{}{sessionName, sessionIdentifier})
	fake.setLogSessionMutex.Unlock()
	if fake.SetLogSessionStub != nil {
		fake.SetLogSessionStub(sessionName, sessionIdentifier)
	}
}

func (fake *FakeBackuper) SetLogSessionCallCount() int {
	fake.setLogSessionMutex.RLock()
	defer fake.setLogSessionMutex.RUnlock()
	return len(fake.setLogSessionArgsForCall)
}

func (fake *FakeBackuper) SetLogSessionArgsForCall(i int) (string, string) {
	fake.setLogSessionMutex.RLock()
	defer fake.setLogSessionMutex.RUnlock()
	return fake.setLogSessionArgsForCall[i].sessionName, fake.setLogSessionArgsForCall[i].sessionIdentifier
}

func (fake *FakeBackuper) CloseLogSession() {
	fake.closeLogSessionMutex.Lock()
	fake.closeLogSessionArgsForCall = append(fake.closeLogSessionArgsForCall, struct{}{})
	fake.recordInvocation("CloseLogSession", []interface{}{})
	fake.closeLogSessionMutex.Unlock()
	if fake.CloseLogSessionStub != nil {
		fake.CloseLogSessionStub()
	}
}

func (fake *FakeBackuper) CloseLogSessionCallCount() int {
	fake.closeLogSessionMutex.RLock()
	defer fake.closeLogSessionMutex.RUnlock()
	return len(fake.closeLogSessionArgsForCall)
}

func (fake *FakeBackuper) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	fake.setLogSessionMutex.RLock()
	defer fake.setLogSessionMutex.RUnlock()
	fake.closeLogSessionMutex.RLock()
	defer fake.closeLogSessionMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeBackuper) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ backup.Backuper = new(FakeBackuper)
