#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/.." && pwd )"

AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:?}"
AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:?}"

pushd "${BASE_DIR}"
  go get -t -v -d ./...
  go install github.com/onsi/ginkgo/ginkgo
  ginkgo \
    -r \
    -p \
    -race \
    -randomizeSuites \
    -randomizeAllSpecs \
    -slowSpecThreshold=30 \
    -keepGoing \
    "$@" \
    s3integration scpintegration
popd
