#!/bin/bash

set -e

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/.." && pwd )"

AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:?}"
AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:?}"
AWS_ACCESS_KEY_ID_RESTRICTED="${AWS_ACCESS_KEY_ID_RESTRICTED:?}"
AWS_SECRET_ACCESS_KEY_RESTRICTED="${AWS_SECRET_ACCESS_KEY_RESTRICTED:?}"
CEPH_ACCESS_KEY_ID="${CEPH_ACCESS_KEY_ID:?}"
CEPH_SECRET_ACCESS_KEY="${CEPH_SECRET_ACCESS_KEY:?}"
CEPH_ENDPOINT_URL="${CEPH_ENDPOINT_URL:?}"
AZURE_STORAGE_ACCOUNT="${AZURE_STORAGE_ACCOUNT:?}"
AZURE_STORAGE_ACCESS_KEY="${AZURE_STORAGE_ACCESS_KEY:?}"

pushd "${BASE_DIR}"
  go get -t -v -d ./...
  go install github.com/onsi/ginkgo/ginkgo
  ginkgo \
    -r \
    -p \
    -race \
    -randomizeSuites \
    -randomizeAllSpecs \
    -slowSpecThreshold=30 \
    -keepGoing \
    -cover \
    "$@" \
    s3integration scpintegration azureintegration backup

    go tool cover -func=backup/backup.coverprofile

popd
