#!/bin/bash

set -e

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/.." && pwd )"

AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:?}"
AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:?}"
AWS_ACCESS_KEY_ID_RESTRICTED="${AWS_ACCESS_KEY_ID_RESTRICTED:?}"
AWS_SECRET_ACCESS_KEY_RESTRICTED="${AWS_SECRET_ACCESS_KEY_RESTRICTED:?}"
AZURE_STORAGE_ACCOUNT="${AZURE_STORAGE_ACCOUNT:?}"
AZURE_STORAGE_ACCESS_KEY="${AZURE_STORAGE_ACCESS_KEY:?}"

pushd "${BASE_DIR}"
  go get -t -v -d ./...
  go install github.com/onsi/ginkgo/ginkgo
  ./scripts/run_parallel_tests.sh -skipPackage scpintegration,release_tests
  ./scripts/run_tests.sh scpintegration

  go tool cover -func=backup/backup.coverprofile
popd
